import Link from 'next/link';
import ResponsiveImage from '@/components/ResponsiveImage';
import Arrow from '@/components/Arrow';
import { locations, programs } from '@/lib/site';

export default function HomePage() {
 return <main>
  <section className="hero"><div className="hero-copy"><div className="eyebrow">WOMEN’S DEVELOPMENT FEDERATION · HAMBANTOTA, SRI LANKA</div><h1>Women.<br/><i>Families.</i><br/><span>Communities.</span></h1><p className="hero-lead">A people-centred organization working across economic and social development to strengthen women, families and communities.</p><div className="actions"><Link className="btn dark" href="/what-we-do">Explore our work <Arrow/></Link><Link className="btn ghost" href="/impact">See our impact</Link></div><div className="hero-note"><span>01</span><div>Founded as a women-led development movement in Hambantota, with a long-standing focus on self-reliance, savings and community action.</div></div></div><div className="hero-visual"><div className="photo photo-main"><ResponsiveImage src="/images/wdf-img-1.jpeg" alt="Women meeting together in a community setting in Sri Lanka"/></div><div className="photo photo-small"><ResponsiveImage src="/images/wdf-img-21.jpeg" alt="Women members sharing and discussing together"/></div><div className="seal">WDF<br/><small>HAM<br/>BANTOTA</small></div></div></section>
  <section className="intro section"><div className="section-label">01 / WHO WE ARE</div><div className="intro-grid"><h2>Development that begins <em>with people.</em></h2><div><p className="large-copy">WDF brings financial and non-financial services together across economic, social, spiritual, environmental and cultural fields to empower women and their families.</p><Link className="text-link" href="/about">Our story &amp; values <Arrow/></Link></div></div></section>
  <section className="stats-band"><div className="section-label light">02 / DOCUMENTED REACH</div><div className="stats-grid">{[[99,'Janashakthi Bank Societies','Network documented in organizational materials'],[449,"Children’s Societies",'Children aged 6–16'],[572,'Senior Citizens’ Societies','Community connection and participation'],[133,'Deavi Societies','Youth groups within the bank network']].map(([n,t,d])=><div className="stat" key={String(t)}><strong>{n}</strong><b>{t}</b><small>{d}</small></div>)}</div><p className="source-note">Figures are presented as documented in the supplied WDF source material; reporting periods vary by source.</p></section>
  <section className="locations section"><div className="section-label">03 / GEOGRAPHICAL AREAS</div><div className="split-head"><h2>Rooted in the <em>South.</em></h2><p>The source material identifies coverage across Hambantota, Monaragala and Ratnapura districts.</p></div><div className="location-grid">{locations.map(([name,count,detail])=><div className="location" key={name}><div className="location-num">{count}</div><h3>{name}</h3><p>{detail}</p></div>)}</div></section>
  <section className="programs section"><div className="section-label">04 / WHAT WE DO</div><div className="split-head"><h2>More than <em>financial services.</em></h2><p>WDF’s work connects economic opportunity with social development, community participation and human development.</p></div><div className="program-grid">{programs.map(([n,t,d])=><Link className="program" key={t} href={t==='Janashakthi Banks'?'/janashakthi-banks':'/what-we-do'}><span>{n}</span><h3>{t}</h3><p>{d}</p><Arrow/></Link>)}</div></section>
  <section className="bank-feature"><div className="bank-image"><ResponsiveImage src="/images/wdf-img-4.jpeg" alt="Women gathered around records at a Janashakthi Bank Society meeting"/></div><div className="bank-copy"><div className="section-label light">05 / JANASHAKTHI BANKS</div><h2>Community finance, <em>built from within.</em></h2><p>The Janashakthi Bank Society model brings women together around savings, credit, participation and income generation.</p><div className="bank-points"><span>SAVINGS</span><span>LOANS</span><span>OWNERSHIP</span><span>COMMUNITY</span></div><Link className="btn light-btn" href="/janashakthi-banks">Explore Janashakthi Banks <Arrow/></Link></div></section>
  <section className="editorial section"><div className="editorial-image"><ResponsiveImage src="/images/wdf-img-12.jpeg" alt="A woman developing sewing skills as part of a livelihood activity"/></div><div className="editorial-copy"><div className="section-label">06 / WOMEN’S EMPOWERMENT</div><h2>Creating pathways to <em>economic independence.</em></h2><p>Women are supported through savings, access to credit, entrepreneurship, vocational training, counselling and community organizations.</p><Link className="text-link" href="/what-we-do">Discover women’s empowerment <Arrow/></Link></div></section>
  <section className="projects-preview section"><div className="section-label">07 / PROJECTS</div><div className="split-head"><h2>Projects rooted in <em>community.</em></h2><Link className="btn outline" href="/projects">View projects <Arrow/></Link></div><div className="project-grid"><article><div className="project-photo"><ResponsiveImage src="/images/wdf-img-23.jpeg" alt="Woman tending leafy vegetables in a home garden"/></div><small>SPECIAL PROJECTS</small><h3>Strong home gardens</h3><p>Households are supported to produce food through composting, vegetables, fruit, milk and leafy greens.</p></article><article><div className="project-photo"><ResponsiveImage src="/images/wdf-img-18.jpeg" alt="Women taking part in a public awareness march"/></div><small>COMMUNITY</small><h3>Women’s rights &amp; leadership</h3><p>Documented initiatives build awareness of women’s rights, leadership and technology-facilitated violence.</p></article><article><div className="project-photo"><ResponsiveImage src="/images/wdf-img-2.jpeg" alt="Children gathered with community members at an activity"/></div><small>YOUTH</small><h3>Deavi youth empowerment</h3><p>Youth societies support leadership, counselling, health awareness, savings and vocational pathways.</p></article></div></section>
  <section className="reports-callout"><div><div className="section-label light">08 / TRANSPARENCY</div><h2>See the numbers behind the work.</h2><p>Explore WDF’s published annual reports and financial information across reporting years.</p></div><Link className="btn light-btn" href="/financials">Financials &amp; reports <Arrow/></Link></section>
  <section className="news-preview section"><div className="section-label">09 / NEWS &amp; MEDIA</div><div className="split-head"><h2>Updates from the <em>Federation.</em></h2><Link className="text-link" href="/news-media">Visit newsroom <Arrow/></Link></div><div className="news-grid"><article><small>NEWSROOM</small><h3>Official WDF updates</h3><p>News, programme updates, organizational milestones and announcements published through the newsroom.</p></article><article><small>EVENTS</small><h3>Community events</h3><p>Upcoming and past activities can be presented as dated stories with photographs and details.</p></article><article><small>MEDIA</small><h3>Media resources</h3><p>Official statements, interviews and media resources can be managed alongside news content.</p></article></div></section>
 </main>;
}
